CREATE TABLE `t_dark_detect_batch` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '批次ID',
  `batch_no` varchar(32) NOT NULL COMMENT '批次编号（唯一）',
  `batch_name` varchar(200) DEFAULT NULL COMMENT '批次名称',
  `total_files` int(11) NOT NULL DEFAULT '0' COMMENT '总文件数',
  `pass_files` int(11) NOT NULL DEFAULT '0' COMMENT '全部通过的文件数',
  `fail_files` int(11) NOT NULL DEFAULT '0' COMMENT '存在违规的文件数',
  `error_files` int(11) NOT NULL DEFAULT '0' COMMENT '检测失败的文件数',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-处理中，1-全部完成，2-部分失败',
  `is_related` tinyint(4) NOT NULL DEFAULT '0' COMMENT '文件是否关联：0-否，1-是',
  `cross_analysis_result` text COMMENT '关联分析报告（JSON格式）',
  `result_summary` text COMMENT '批次结果摘要（JSON）',
  `creator_name` varchar(50) NOT NULL COMMENT '创建人姓名',
  `updater_name` varchar(50) DEFAULT NULL COMMENT '更新人姓名',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_no` (`batch_no`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_creator_name` (`creator_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='暗标检测批次表';

CREATE TABLE `t_dark_detect_task` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `batch_id` bigint(20) NOT NULL COMMENT '所属批次ID',
  `task_no` varchar(32) NOT NULL COMMENT '任务编号（唯一）',
  `file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `file_path` varchar(500) NOT NULL COMMENT '文件存储路径',
  `file_size` bigint(20) DEFAULT NULL COMMENT '文件大小（字节）',
  `file_type` tinyint(4) DEFAULT NULL COMMENT '1-DOCX，2-PDF',
  `file_order` int(11) DEFAULT '0' COMMENT '文件在批次中的序号',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-排队中，1-检测中，2-已完成，3-失败',
  `total_rules` int(11) DEFAULT '0' COMMENT '总检测规则数',
  `pass_rules` int(11) DEFAULT '0' COMMENT '通过规则数',
  `fail_rules` int(11) DEFAULT '0' COMMENT '不通过规则数',
  `result_summary` text COMMENT '检测结果摘要（JSON）',
  `error_msg` varchar(500) DEFAULT NULL COMMENT '失败时的错误信息',
  `creator_name` varchar(50) NOT NULL COMMENT '创建人姓名',
  `updater_name` varchar(50) DEFAULT NULL COMMENT '更新人姓名',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  KEY `idx_batch_id` (`batch_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='暗标检测任务表';

CREATE TABLE `t_dark_detect_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '结果ID',
  `task_id` bigint(20) NOT NULL COMMENT '任务ID',
  `rule_code` varchar(50) NOT NULL COMMENT '规则编码',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `rule_category` varchar(50) DEFAULT NULL COMMENT '规则分类：layout/font/table/sensitive',
  `page_no` int(11) DEFAULT NULL COMMENT '违规所在页码',
  `paragraph_index` int(11) DEFAULT NULL COMMENT '违规所在段落索引',
  `actual_value` varchar(500) DEFAULT NULL COMMENT '实际检测值',
  `expected_value` varchar(500) DEFAULT NULL COMMENT '期望值',
  `is_pass` tinyint(4) NOT NULL COMMENT '0-不通过，1-通过',
  `severity` tinyint(4) DEFAULT '1' COMMENT '1-警告，2-一般，3-严重',
  `remark` varchar(500) DEFAULT NULL COMMENT '修改建议',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_rule_code` (`rule_code`),
  KEY `idx_is_pass` (`is_pass`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单文件检测结果详情表';

CREATE TABLE `t_dark_detect_cross_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '结果ID',
  `batch_id` bigint(20) NOT NULL COMMENT '批次ID',
  `analysis_type` varchar(50) NOT NULL COMMENT '分析类型：SENSITIVE_CROSS-敏感词跨文件合并，FORMAT_CONSISTENCY-格式一致性',
  `analysis_name` varchar(100) NOT NULL COMMENT '分析名称',
  `involved_files` text COMMENT '涉及的文件列表（JSON数组）',
  `actual_value` text COMMENT '实际检测值',
  `expected_value` varchar(500) DEFAULT NULL COMMENT '期望值',
  `is_pass` tinyint(4) NOT NULL COMMENT '0-不通过，1-通过',
  `severity` tinyint(4) DEFAULT '1' COMMENT '1-警告，2-一般，3-严重',
  `remark` varchar(500) DEFAULT NULL COMMENT '修改建议',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_batch_id` (`batch_id`),
  KEY `idx_analysis_type` (`analysis_type`),
  KEY `idx_is_pass` (`is_pass`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='关联分析结果表';

CREATE TABLE `t_dark_rule_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '配置ID',
  `rule_code` varchar(50) NOT NULL COMMENT '规则编码（固定值）',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `rule_category` varchar(50) NOT NULL COMMENT '分类：layout/font/table/sensitive/cross',
  `param_key` varchar(50) NOT NULL COMMENT '参数键',
  `param_name` varchar(100) DEFAULT NULL COMMENT '参数显示名称',
  `param_value` varchar(200) NOT NULL COMMENT '参数值',
  `param_unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `sort_order` int(11) DEFAULT '0' COMMENT '排序',
  `enabled` tinyint(4) NOT NULL DEFAULT '1' COMMENT '0-禁用，1-启用',
  `creator_name` varchar(50) NOT NULL COMMENT '创建人姓名',
  `updater_name` varchar(50) DEFAULT NULL COMMENT '更新人姓名',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_param` (`rule_code`, `param_key`),
  KEY `idx_rule_code` (`rule_code`),
  KEY `idx_category` (`rule_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检测规则配置表';

CREATE TABLE `t_dark_sensitive_category` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `category_name` varchar(50) NOT NULL COMMENT '分类名称（如：投标招标、联系方式）',
  `sort_order` int(11) DEFAULT '0' COMMENT '排序（前端展示顺序）',
  `enabled` tinyint(4) NOT NULL DEFAULT '1' COMMENT '0-禁用，1-启用',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `creator_name` varchar(50) NOT NULL COMMENT '创建人姓名',
  `updater_name` varchar(50) DEFAULT NULL COMMENT '更新人姓名',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词分类表';

CREATE TABLE `t_dark_sensitive_word` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '敏感词ID',
  `category_id` bigint(20) NOT NULL COMMENT '所属分类ID（关联t_dark_sensitive_category.id）',
  `word` varchar(100) NOT NULL COMMENT '敏感词内容',
  `enabled` tinyint(4) NOT NULL DEFAULT '1' COMMENT '0-禁用，1-启用',
  `creator_name` varchar(50) NOT NULL COMMENT '创建人姓名',
  `updater_name` varchar(50) DEFAULT NULL COMMENT '更新人姓名',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_word` (`word`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词表';

INSERT INTO t_dark_sensitive_category (category_name, sort_order, enabled, creator_name, create_time, del_flag) VALUES
('投标招标', 1, 1, 'admin', NOW(), 0),
('联系方式', 2, 1, 'admin', NOW(), 0),
('地理位置', 3, 1, 'admin', NOW(), 0),
('网络信息', 4, 1, 'admin', NOW(), 0),
('版权信息', 5, 1, 'admin', NOW(), 0),
('作者信息', 6, 1, 'admin', NOW(), 0),
('落地案例', 7, 1, 'admin', NOW(), 0),
('奖项荣誉', 8, 1, 'admin', NOW(), 0),
('专利信息', 9, 1, 'admin', NOW(), 0),
('其他', 10, 1, 'admin', NOW(), 0);

INSERT INTO t_dark_sensitive_word (category_id, word, enabled, creator_name, create_time, del_flag) VALUES
-- 投标招标 (category_id=1)
(1, '投标', 1, 'admin', NOW(), 0),
(1, '招标', 1, 'admin', NOW(), 0),
(1, '标书', 1, 'admin', NOW(), 0),
(1, '竞标', 1, 'admin', NOW(), 0),
-- 联系方式 (category_id=2)
(2, '团队', 1, 'admin', NOW(), 0),
(2, '联系', 1, 'admin', NOW(), 0),
(2, '电话', 1, 'admin', NOW(), 0),
(2, '邮箱', 1, 'admin', NOW(), 0),
(2, '地址', 1, 'admin', NOW(), 0),
(2, '手机', 1, 'admin', NOW(), 0),
(2, '传真', 1, 'admin', NOW(), 0),
(2, '热线', 1, 'admin', NOW(), 0),
(2, '姓名', 1, 'admin', NOW(), 0),
(2, '有限公司', 1, 'admin', NOW(), 0),
(2, '有限责任公司', 1, 'admin', NOW(), 0),
(2, '有限股份公司', 1, 'admin', NOW(), 0),
-- 地理位置 (category_id=3)
(3, '省', 1, 'admin', NOW(), 0),
(3, '市', 1, 'admin', NOW(), 0),
(3, '县', 1, 'admin', NOW(), 0),
(3, '区', 1, 'admin', NOW(), 0),
(3, '街道', 1, 'admin', NOW(), 0),
(3, '路', 1, 'admin', NOW(), 0),
(3, '巷', 1, 'admin', NOW(), 0),
(3, '村', 1, 'admin', NOW(), 0),
(3, '镇', 1, 'admin', NOW(), 0),
(3, '乡', 1, 'admin', NOW(), 0),
-- 网络信息 (category_id=4)
(4, '网址', 1, 'admin', NOW(), 0),
(4, '网站', 1, 'admin', NOW(), 0),
(4, '链接', 1, 'admin', NOW(), 0),
(4, 'URL', 1, 'admin', NOW(), 0),
(4, '域名', 1, 'admin', NOW(), 0),
(4, 'IP', 1, 'admin', NOW(), 0),
-- 版权信息 (category_id=5)
(5, 'copyright', 1, 'admin', NOW(), 0),
(5, '版权所有', 1, 'admin', NOW(), 0),
(5, '©', 1, 'admin', NOW(), 0),
(5, '®', 1, 'admin', NOW(), 0),
(5, '™', 1, 'admin', NOW(), 0),
(5, '专利', 1, 'admin', NOW(), 0),
(5, '商标', 1, 'admin', NOW(), 0),
-- 作者信息 (category_id=6)
(6, 'author', 1, 'admin', NOW(), 0),
(6, '作者', 1, 'admin', NOW(), 0),
(6, '编写', 1, 'admin', NOW(), 0),
(6, '撰写', 1, 'admin', NOW(), 0),
-- 落地案例 (category_id=7)
(7, '落地', 1, 'admin', NOW(), 0),
(7, '案例', 1, 'admin', NOW(), 0),
(7, '实例', 1, 'admin', NOW(), 0),
(7, '实践', 1, 'admin', NOW(), 0),
(7, '应用', 1, 'admin', NOW(), 0),
(7, '实施', 1, 'admin', NOW(), 0),
-- 奖项荣誉 (category_id=8)
(8, '奖项', 1, 'admin', NOW(), 0),
(8, '荣誉', 1, 'admin', NOW(), 0),
(8, '获奖', 1, 'admin', NOW(), 0),
(8, '金奖', 1, 'admin', NOW(), 0),
(8, '银奖', 1, 'admin', NOW(), 0),
(8, '铜奖', 1, 'admin', NOW(), 0),
(8, '一等奖', 1, 'admin', NOW(), 0),
(8, '二等奖', 1, 'admin', NOW(), 0),
(8, '三等奖', 1, 'admin', NOW(), 0),
-- 专利信息 (category_id=9)
(9, '专利', 1, 'admin', NOW(), 0),
(9, '发明专利', 1, 'admin', NOW(), 0),
(9, '实用新型', 1, 'admin', NOW(), 0),
(9, '外观设计', 1, 'admin', NOW(), 0),
(9, '专利号', 1, 'admin', NOW(), 0),
(9, '专利申请', 1, 'admin', NOW(), 0);

