spring:
  datasource:
    druid:
      driver-class-name: ${SPRING_DATASOURCE_DRUID_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
      url: ${SPRING_DATASOURCE_DRUID_URL:jdbc:mysql://localhost:3306/renren_security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true}
      username: ${SPRING_DATASOURCE_DRUID_USERNAME:renren}
      password: ${SPRING_DATASOURCE_DRUID_PASSWORD:123456}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

paddle:
  enabled: ${PADDLE_ENABLED:true}
  model.path: ${PADDLE_MODEL_PATH:/app/models}

upload:
  path: ${UPLOAD_PATH:/app/upload}